Auto update packages (#249)

diff --git a/bin/github-repo-metadata b/bin/github-repo-metadata
--- a/bin/github-repo-metadata
+++ b/bin/github-repo-metadata
@@ -2,11 +2,13 @@
 # Use bash to keep this from accidentally running under Alpine/Codefresh
 # Switch to sh to allow use in Alpine. The script works either way.
 
+set -o pipefail
+
 function fetch() {
-  local org=$1
-  local repo=$2
-  local api=$3
-  local path=$4
+  local org="$1"
+  local repo="$2"
+  local api="$3"
+  local path="$4"
   local header=""
 
   if [ -n "$GITHUB_TOKEN" ] ; then
@@ -19,9 +21,13 @@ function fetch() {
     api="/${api}"
   fi
 
-  local ref=$(curl -sSL -H "$header" "https://api.github.com/repos/$org/${repo}${api}" | jq -r "$path")
+  local url="https://api.github.com/repos/$org/${repo}${api}"
+  local ref=$(curl -fsSL -H "$header" "${url}" | jq -r "$path")
   if [ $? -eq 0 ]; then
     echo $ref
+  else
+    echo "ERROR: Failed to retrieve ${url}" >&2
+    exit 1
   fi
 }
 
@@ -34,4 +40,3 @@ else
   echo "       $0 cloudposse geodesic '' .description"
   exit 1
 fi
-
