Enable auto-update for version-pinned packages (#671)

diff --git a/tasks/Makefile.package b/tasks/Makefile.package
--- a/tasks/Makefile.package
+++ b/tasks/Makefile.package
@@ -4,7 +4,8 @@ export OS ?= $(shell uname -s | tr '[:upper:]' '[:lower:'])
 export OS_ARCH ?= $(shell uname -m)
 export INSTALL_PATH ?= /usr/local/bin
 export CURL ?= curl --retry 3 --retry-delay 5 --fail -sSL
-export PATH := $(PATH):../../bin/
+export LOCAL_BIN := ../../bin
+export PATH := $(PATH):$(LOCAL_BIN)
 export SHELL := /bin/bash
 
 export TMP ?= /tmp
@@ -20,6 +21,12 @@ export PACKAGE_RELEASE ?= $(shell cat RELEASE 2>/dev/null)
 export PACKAGE_LICENSE ?= $(shell cat LICENSE 2>/dev/null)
 export PACKAGE_HOMEPAGE_URL ?= https://github.com/$(VENDOR)/$(PACKAGE)
 export PACKAGE_REPO_URL ?= https://github.com/$(VENDOR)/$(PACKAGE_REPO_NAME)
+
+ifeq ($(strip $(PACKAGE_VERSION_PIN)),)
+	export PACKAGE_VERSION_TARGET = CURRENT_VERSION
+else
+	export PACKAGE_VERSION_TARGET = PINNED_VERSION
+endif
 
 export AUTO_UPDATE_ENABLED ?= true
 
@@ -85,6 +92,18 @@ endef
 download/tar/bz2:
 	$(call download_tar_bz2)
 
+define download_tar_gz
+	[ -n "$(TMP)" ] && [ -n "$(PACKAGE_NAME)" ] && rm -rf "$(TMP)/$(PACKAGE_NAME)"
+	mkdir -p $(TMP)/$(PACKAGE_NAME)
+	$(CURL) -o - $(DOWNLOAD_URL) | tar -zx -C $(TMP)/$(PACKAGE_NAME)
+	find $(TMP)/$(PACKAGE_NAME) -type f -name $(PACKAGE_NAME) | xargs -I {} cp -f {} $(INSTALL_PATH)/$(PACKAGE_EXE)
+	chmod +x $(INSTALL_PATH)/$(PACKAGE_EXE)
+	[ -n "$(TMP)" ] && [ -n "$(PACKAGE_NAME)" ] && rm -rf "$(TMP)/$(PACKAGE_NAME)"
+endef
+
+download/tar/gz:
+	$(call download_tar_gz)
+
 define download_tar_xz
 	[ -n "$(TMP)" ] && [ -n "$(PACKAGE_NAME)" ] && rm -rf "$(TMP)/$(PACKAGE_NAME)"
 	mkdir -p $(TMP)/$(PACKAGE_NAME)
@@ -125,22 +144,17 @@ download/gz:
 
 default: info
 
+# Only works if current working directory is under vendor/
+$(LOCAL_BIN)/vert: INSTALL_PATH = $(LOCAL_BIN)
+$(LOCAL_BIN)/vert:
+	$(MAKE) -C ../vert install
+
 DESCRIPTION:
 	@github-repo-metadata $(VENDOR) $(PACKAGE_REPO_NAME) "index" .description | tee DESCRIPTION
 
-VERSION: API=releases/latest
-VERSION: QUERY=.tag_name
-VERSION:
-	@version=$$(github-repo-metadata $(VENDOR) $(PACKAGE_REPO_NAME) '$(API)' '$(QUERY)' | sed 's/^v//' | tr -d '\n'); \
-	if [ $$? -ne 0 ]; then \
-		exit 1; \
-	fi; \
-	if [ "$${version}" == "null" -o "$${version}" == "" ]; then \
-		echo "ERROR: failed to obtain current version for $(VENDOR)/$(PACKAGE_REPO_NAME)"; \
-		exit 1; \
-	else \
-		echo "$${version}" | tee VERSION; \
-	fi
+# In order to support static configuration of version, the VERSION file should be
+# considered up-to-date unless explicitly updated via the "update" target
+# VERSION:
 
 LICENSE:
 	@github-repo-metadata $(VENDOR) $(PACKAGE_REPO_NAME) "license" .license.spdx_id | tr '[:lower:]' '[:upper:]' | tee LICENSE
@@ -159,9 +173,13 @@ RELEASE: VERSION LICENSE DESCRIPTION
 		fi; \
 	fi
 
-init: VERSION LICENSE DESCRIPTION RELEASE
+init: AUTO_UPDATE_ENABLED=true
+init: $(PACKAGE_VERSION_TARGET) LICENSE DESCRIPTION RELEASE
 
-update: CURRENT_VERSION RELEASE
+update: $(PACKAGE_VERSION_TARGET) RELEASE
+
+force-update: AUTO_UPDATE_ENABLED=true
+force-update: $(PACKAGE_VERSION_TARGET) RELEASE
 
 sleep: RATE_LIMIT=0
 sleep:
@@ -177,7 +195,7 @@ auto-update:
 	fi
 
 # The only way to tell if VERSION is up to date is to query the source via the internet
-.PHONY: CURRENT_VERSION
+.PHONY: CURRENT_VERSION PINNED_VERSION
 
 # Update the VERSION file only if it would change, to avoid triggering unnecessary builds
 CURRENT_VERSION: API=releases/latest
@@ -188,16 +206,41 @@ CURRENT_VERSION:
 	if [ $$? -ne 0 ]; then \
 		exit 1; \
 	elif [ "$${current_version}" == "null" -o -z "$${current_version}" ]; then \
-		echo "ERROR: failed to obtain current version for $(VENDOR)/$(PACKAGE_REPO_NAME) (got: $${current_version})"; \
+		echo "ERROR: failed to obtain current version for $(VENDOR)/$(PACKAGE_REPO_NAME) (got: $${current_version})" >&2; \
 		exit 1; \
 	elif [ "$${local_version}" != "$${current_version}" ]; then \
 		if [ $$(semver "$${current_version}" "$${local_version}" ) != "1" ]; then \
-			echo "NOT \"Upgrading\" $(PACKAGE_NAME) from $${local_version} to OLDER $${current_version}"; \
-		else \
+			echo "NOT \"Upgrading\" $(PACKAGE_NAME) from $${local_version} to OLDER $${current_version}" >&2; \
+		elif [ "$${AUTO_UPDATE_ENABLED:-true}" == "true" ]; then \
 		 	echo "Upgrading $(PACKAGE_NAME) from $${local_version} to $${current_version}"; \
 			echo "$${current_version}" > VERSION; \
+		else \
+			echo "NOT \"Upgrading\" $(PACKAGE_NAME) from $${local_version} to $${current_version} because auto-update is disabled" >&2; \
 		fi \
 	fi
+
+PINNED_VERSION: API=releases?per_page=100
+PINNED_VERSION: QUERY=.[].tag_name
+PINNED_VERSION: $(LOCAL_BIN)/vert
+	@local_version=$$(cat VERSION || echo 0); \
+	current_version=$$(env PATH='$(PATH)' vert -s '$(PACKAGE_VERSION_PIN)' \
+	  $$(env PATH='$(PATH)' github-repo-metadata $(VENDOR) $(PACKAGE_REPO_NAME) '$(API)' '$(QUERY)') | tail -1); \
+	if [ $$? -ne 0 ]; then \
+		exit 1; \
+	elif [ "$${current_version}" == "null" -o -z "$${current_version}" ]; then \
+		echo "ERROR: failed to obtain version matching '$(PACKAGE_VERSION_PIN)' for $(VENDOR)/$(PACKAGE_REPO_NAME) (got: $${current_version})" >&2; \
+		exit 1; \
+	elif [ "$${local_version}" != "$${current_version}" ]; then \
+		if [ $$(semver "$${current_version}" "$${local_version}" ) != "1" ]; then \
+			echo "NOT \"Upgrading\" $(PACKAGE_NAME) from $${local_version} to OLDER $${current_version}" >&2; \
+		elif [ "$${AUTO_UPDATE_ENABLED:-true}" == "true" ]; then \
+		 	echo "Upgrading $(PACKAGE_NAME) from $${local_version} to $${current_version}"; \
+			echo "$${current_version}" > VERSION; \
+		else \
+			echo "NOT \"Upgrading\" $(PACKAGE_NAME) from $${local_version} to $${current_version} because auto-update is disabled" >&2; \
+		fi \
+	fi
+
 
 info:
 	@printf "%-20s %s\n" "Vendor:" "$(VENDOR)"
